server:
  port: 8888

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8080/eureka/
  instance:
    prefer-ip-address: true
    non-secure-port: ${server.port}

spring:
  application:
    name: eureka-consumer